#!/usr/bin/env python3
import json
import os
import re
import shlex
import ssl
import time
import unicodedata
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


BASH_CALL_ID = "agentsmith_lite_local_bash"
PUBLISH_CALL_ID = "agentsmith_lite_local_publish_file"
ARTIFACT_FILENAME = "artifact.txt"
ARTIFACT_CONTENT = "AgentSmith Lite local OpenAI provider artifact"


def tool_names(body):
    names = set()
    for tool in body.get("tools") or []:
        function = tool.get("function") if isinstance(tool, dict) else None
        name = function.get("name") if isinstance(function, dict) else None
        if isinstance(name, str):
            names.add(name)
    return names


def has_tool_result(messages, tool_call_id):
    for message in messages:
        if not isinstance(message, dict):
            continue
        if message.get("role") == "tool" and message.get("tool_call_id") == tool_call_id:
            return True
    return False


def latest_user_text(messages):
    for message in reversed(messages):
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        content = message.get("content")
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            parts = []
            for part in content:
                if isinstance(part, dict):
                    text = part.get("text")
                    if isinstance(text, str):
                        parts.append(text)
            if parts:
                return " ".join(parts)
    return "message received"


def artifact_contract(messages):
    text = latest_user_text(messages)
    return {
        "filename": prompt_artifact_filename(text) or ARTIFACT_FILENAME,
        "content": prompt_artifact_marker(text) or ARTIFACT_CONTENT,
    }


def normalize_artifact_filename(filename):
    if not isinstance(filename, str):
        return None
    filename = unicodedata.normalize("NFC", filename)
    if (
        not filename
        or filename in {".", ".."}
        or "/" in filename
        or "\\" in filename
        or not filename.isprintable()
        or len(filename.encode("utf-8")) > 128
    ):
        return None
    return filename


def prompt_artifact_filename(text):
    for pattern in (r"\bfilename\s+([^\s]+)", r"\bcreate\s+([^\s]+)"):
        match = re.search(pattern, text)
        if not match:
            continue
        candidate = match.group(1).strip("`'\"").rstrip(".,;:")
        filename = normalize_artifact_filename(candidate)
        if filename:
            return filename
    return None


def prompt_artifact_marker(text):
    match = re.search(r"exact marker on its own line:\s*([^\r\n]+)", text)
    if not match:
        return None
    marker = match.group(1).strip()
    if marker.endswith("."):
        marker = marker[:-1]
    return marker or None


def artifact_write_command(filename, content):
    quoted_filename = shlex.quote(filename)
    quoted_content = shlex.quote(content)
    return f"printf '%s\\n' {quoted_content} > {quoted_filename}; printf '%s\\n' {quoted_filename}"


def tool_call(call_id, name, arguments):
    return {
        "id": call_id,
        "type": "function",
        "function": {
            "name": name,
            "arguments": arguments_json(arguments),
        },
    }


def arguments_json(arguments):
    if not isinstance(arguments, dict):
        arguments = {}
    return json.dumps({key: value for key, value in arguments.items()}, separators=(",", ":"))


def assistant_response(body):
    model = body.get("model") if isinstance(body.get("model"), str) else "local-openai-dev"
    messages = body.get("messages") if isinstance(body.get("messages"), list) else []
    tools = tool_names(body)

    if "bash" in tools or "publish_file" in tools:
        artifact = artifact_contract(messages)
        if has_tool_result(messages, PUBLISH_CALL_ID):
            return completion(model, {"role": "assistant", "content": "Local artifact published."}, "stop")
        if has_tool_result(messages, BASH_CALL_ID) and "publish_file" in tools:
            return completion(
                model,
                {
                    "role": "assistant",
                    "content": None,
                    "tool_calls": [
                        tool_call(
                            PUBLISH_CALL_ID,
                            "publish_file",
                            {
                                "path": artifact["filename"],
                                "filename": artifact["filename"],
                                "mime_type": "text/plain",
                                "description": "Generated by the local OpenAI-compatible dev provider",
                            },
                        )
                    ],
                },
                "tool_calls",
            )
        if "bash" in tools:
            command = artifact_write_command(artifact["filename"], artifact["content"])
            return completion(
                model,
                {
                    "role": "assistant",
                    "content": None,
                    "tool_calls": [
                        tool_call(
                            BASH_CALL_ID,
                            "bash",
                            {
                                "command": command,
                                "timeout_secs": 10,
                            },
                        )
                    ],
                },
                "tool_calls",
            )

    text = latest_user_text(messages)
    return completion(
        model,
        {"role": "assistant", "content": f"local OpenAI-compatible provider response: {text}"},
        "stop",
    )


def completion(model, message, finish_reason):
    prompt_tokens = 1
    completion_tokens = 1
    return {
        "id": f"chatcmpl-local-{uuid.uuid4().hex[:16]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [
            {
                "index": 0,
                "message": message,
                "finish_reason": finish_reason,
            }
        ],
        "usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": prompt_tokens + completion_tokens,
        },
    }


def completion_chunk(response):
    choice = response["choices"][0]
    message = choice["message"]
    delta = {}
    if message.get("tool_calls"):
        delta["tool_calls"] = [
            {
                "index": index,
                "id": call["id"],
                "type": call["type"],
                "function": {
                    "name": call["function"]["name"],
                    "arguments": call["function"]["arguments"],
                },
            }
            for index, call in enumerate(message["tool_calls"])
        ]
    else:
        delta["content"] = message.get("content") or ""
    return {
        "id": response["id"],
        "object": "chat.completion.chunk",
        "created": response["created"],
        "model": response["model"],
        "choices": [
            {
                "index": 0,
                "delta": delta,
                "finish_reason": choice["finish_reason"],
            }
        ],
    }


class Handler(BaseHTTPRequestHandler):
    server_version = "AgentSmithLiteLocalOpenAI/1.0"

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args), flush=True)

    def do_GET(self):
        if self.path == "/healthz":
            self.send_response(200)
            self.send_header("content-type", "text/plain; charset=utf-8")
            self.end_headers()
            self.wfile.write(b"ok\n")
            return
        self.send_json(404, {"error": {"message": "not found", "type": "not_found"}})

    def do_POST(self):
        if self.path != "/v1/chat/completions":
            self.send_json(404, {"error": {"message": "not found", "type": "not_found"}})
            return
        expected = os.environ.get("LOCAL_OPENAI_API_KEY", "")
        if not expected or self.headers.get("Authorization") != f"Bearer {expected}":
            self.send_json(401, {"error": {"message": "unauthorized", "type": "invalid_auth"}})
            return
        try:
            length = int(self.headers.get("content-length", "0"))
            body = json.loads(self.rfile.read(length).decode("utf-8"))
        except Exception:
            self.send_json(400, {"error": {"message": "invalid JSON body", "type": "invalid_request"}})
            return

        payload = body if isinstance(body, dict) else {}
        response = assistant_response(payload)
        if payload.get("stream") is True:
            self.send_stream(response)
        else:
            self.send_json(200, response)

    def send_json(self, status, payload):
        data = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def send_stream(self, response):
        frames = [
            completion_chunk(response),
            {
                "id": response["id"],
                "object": "chat.completion.chunk",
                "created": response["created"],
                "model": response["model"],
                "choices": [],
                "usage": response["usage"],
            },
        ]
        self.send_response(200)
        self.send_header("content-type", "text/event-stream")
        self.send_header("cache-control", "no-cache")
        self.end_headers()
        for frame in frames:
            self.wfile.write(b"data: ")
            self.wfile.write(json.dumps(frame, separators=(",", ":")).encode("utf-8"))
            self.wfile.write(b"\n\n")
        self.wfile.write(b"data: [DONE]\n\n")


def main():
    port = int(os.environ.get("PORT", "8443"))
    cert_file = os.environ.get("TLS_CERT_FILE", "/tls/tls.crt")
    key_file = os.environ.get("TLS_KEY_FILE", "/tls/tls.key")
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certfile=cert_file, keyfile=key_file)
    server.socket = context.wrap_socket(server.socket, server_side=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
