apiVersion: v1
kind: Secret
metadata:
  name: ${JUICEFS_SECRET_NAME}
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  name: ${JUICEFS_VOLUME_NAME}
  metaurl: ${JUICEFS_META_URL}
  storage: s3
  bucket: ${JUICEFS_BUCKET}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
